# Generated by Django 4.1.1 on 2022-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_post_location_alter_post_caption_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
